all : gcc - pedantic - Werror - Wall - Wextra - Wvla - std =
    c99 - D_DEFAULT_SOURCE - fsanitize =
        address - g - c - o allocator.o allocator.c gcc - pedantic - Werror
    - Wall - Wextra - Wvla - std = c99 - D_DEFAULT_SOURCE - fsanitize =
            address - g - c - o main.o main.c gcc - pedantic - Werror - Wall
    - Wextra - Wvla - std = c99 - D_DEFAULT_SOURCE - fsanitize =
                address - g - c - o utils.o utils.c gcc - fsanitize =
                    address allocator.o main.o utils.o - o allocator
